### ISSUE TITLE
fix: 후보 데이터를 가져올 때 HTTP 500 발생

### ISSUE THREAD

**Issue by nestiank** [NullFull/call22nd#28]
후보자 명단을 가져올 때 옆의 질문, 응답, 이메일, SNS 데이터를 가져와야 하는데 HTTP 500이 발생합니다.

**Comment by koremp** [comment]
<img width="706" alt="image" src="https://github.com/NullFull/call22nd/assets/18482476/940661e6-badb-409c-94a9-244ccaa5f432">
https://call22nd.works/api/candidates/100153265

**Comment by koremp** [comment]
```
FirebaseAppError: Failed to parse private key: Error: Invalid PEM formatted message.
    at new ServiceAccount (/var/task/node_modules/firebase-admin/lib/app/credential-internal.js:153:19)
    at new ServiceAccountCredential (/var/task/node_modules/firebase-admin/lib/app/credential-internal.js:70:15)
    at Object.cert (/var/task/node_modules/firebase-admin/lib/app/credential-factory.js:103:54)
    at n (/var/task/.next/server/pages/api/candidates/[cid].js:1:1102)
    at /var/task/.next/server/pages/api/candidates/[cid].js:1:685
    at d (/var/task/.next/server/pages/api/candidates/[cid].js:1:725)
    at /var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16638
    at /var/task/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518) {
  errorInfo: {
    code: 'app/invalid-credential',
    message: 'Failed to parse private key: Error: Invalid PEM formatted message.'
  },
  codePrefix: 'app'
}
 ⨯ FirebaseAppError: Failed to parse private key: Error: Invalid PEM formatted message.
    at new ServiceAccount (/var/task/node_modules/firebase-admin/lib/app/credential-internal.js:153:19)
    at new ServiceAccountCredential (/var/task/node_modules/firebase-admin/lib/app/credential-internal.js:70:15)
    at Object.cert (/var/task/node_modules/firebase-admin/lib/app/credential-factory.js:103:54)
    at n (/var/task/.next/server/pages/api/candidates/[cid].js:1:1102)
    at /var/task/.next/server/pages/api/candidates/[cid].js:1:685
    at d (/var/task/.next/server/pages/api/candidates/[cid].js:1:725)
    at /var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16638
    at /var/task/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518) {
  errorInfo: {
    code: 'app/invalid-credential',
    message: 'Failed to parse private key: Error: Invalid PEM formatted message.'
  },
  codePrefix: 'app'
}
FirebaseAppError: Failed to parse private key: Error: Invalid PEM formatted message.
    at new ServiceAccount (/var/task/node_modules/firebase-admin/lib/app/credential-internal.js:153:19)
    at new ServiceAccountCredential (/var/task/node_modules/firebase-admin/lib/app/credential-internal.js:70:15)
    at Object.cert (/var/task/node_modules/firebase-admin/lib/app/credential-factory.js:103:54)
    at n (/var/task/.next/server/pages/api/candidates/[cid].js:1:1102)
    at /var/task/.next/server/pages/api/candidates/[cid].js:1:685
    at d (/var/task/.next/server/pages/api/candidates/[cid].js:1:725)
    at /var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16638
    at /var/task/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518) {
  errorInfo: {
    code: 'app/invalid-credential',
    message: 'Failed to parse private key: Error: Invalid PEM formatted message.'
  },
  codePrefix: 'app'
}
Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by nestiank** [comment]
Firebase DB에 누락된 필드가 있어서 500이 뜨는 거였습니다.
코드를 고칠 필요가 없으므로 닫습니다.
